// Generated by gencpp from file mobile_robot/amclPoseResponse.msg
// DO NOT EDIT!


#ifndef MOBILE_ROBOT_MESSAGE_AMCLPOSERESPONSE_H
#define MOBILE_ROBOT_MESSAGE_AMCLPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_robot
{
template <class ContainerAllocator>
struct amclPoseResponse_
{
  typedef amclPoseResponse_<ContainerAllocator> Type;

  amclPoseResponse_()
    : pos_x(0.0)
    , pos_y(0.0)  {
    }
  amclPoseResponse_(const ContainerAllocator& _alloc)
    : pos_x(0.0)
    , pos_y(0.0)  {
  (void)_alloc;
    }



   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;





  typedef boost::shared_ptr< ::mobile_robot::amclPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_robot::amclPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct amclPoseResponse_

typedef ::mobile_robot::amclPoseResponse_<std::allocator<void> > amclPoseResponse;

typedef boost::shared_ptr< ::mobile_robot::amclPoseResponse > amclPoseResponsePtr;
typedef boost::shared_ptr< ::mobile_robot::amclPoseResponse const> amclPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_robot::amclPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_robot::amclPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_robot::amclPoseResponse_<ContainerAllocator1> & lhs, const ::mobile_robot::amclPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_robot::amclPoseResponse_<ContainerAllocator1> & lhs, const ::mobile_robot::amclPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::amclPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::amclPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::amclPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::amclPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::amclPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::amclPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_robot::amclPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2178591bb5b4f72502724261422523b6";
  }

  static const char* value(const ::mobile_robot::amclPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2178591bb5b4f725ULL;
  static const uint64_t static_value2 = 0x02724261422523b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_robot::amclPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_robot/amclPoseResponse";
  }

  static const char* value(const ::mobile_robot::amclPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_robot::amclPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_x\n"
"float32 pos_y\n"
"\n"
;
  }

  static const char* value(const ::mobile_robot::amclPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_robot::amclPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
      stream.next(m.pos_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct amclPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_robot::amclPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_robot::amclPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_ROBOT_MESSAGE_AMCLPOSERESPONSE_H
