// Generated by gencpp from file mobile_robot/amclPose.msg
// DO NOT EDIT!


#ifndef MOBILE_ROBOT_MESSAGE_AMCLPOSE_H
#define MOBILE_ROBOT_MESSAGE_AMCLPOSE_H

#include <ros/service_traits.h>


#include <mobile_robot/amclPoseRequest.h>
#include <mobile_robot/amclPoseResponse.h>


namespace mobile_robot
{

struct amclPose
{

typedef amclPoseRequest Request;
typedef amclPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct amclPose
} // namespace mobile_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mobile_robot::amclPose > {
  static const char* value()
  {
    return "93e35a8b398245d681b8a701db81ea2e";
  }

  static const char* value(const ::mobile_robot::amclPose&) { return value(); }
};

template<>
struct DataType< ::mobile_robot::amclPose > {
  static const char* value()
  {
    return "mobile_robot/amclPose";
  }

  static const char* value(const ::mobile_robot::amclPose&) { return value(); }
};


// service_traits::MD5Sum< ::mobile_robot::amclPoseRequest> should match
// service_traits::MD5Sum< ::mobile_robot::amclPose >
template<>
struct MD5Sum< ::mobile_robot::amclPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mobile_robot::amclPose >::value();
  }
  static const char* value(const ::mobile_robot::amclPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobile_robot::amclPoseRequest> should match
// service_traits::DataType< ::mobile_robot::amclPose >
template<>
struct DataType< ::mobile_robot::amclPoseRequest>
{
  static const char* value()
  {
    return DataType< ::mobile_robot::amclPose >::value();
  }
  static const char* value(const ::mobile_robot::amclPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mobile_robot::amclPoseResponse> should match
// service_traits::MD5Sum< ::mobile_robot::amclPose >
template<>
struct MD5Sum< ::mobile_robot::amclPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mobile_robot::amclPose >::value();
  }
  static const char* value(const ::mobile_robot::amclPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobile_robot::amclPoseResponse> should match
// service_traits::DataType< ::mobile_robot::amclPose >
template<>
struct DataType< ::mobile_robot::amclPoseResponse>
{
  static const char* value()
  {
    return DataType< ::mobile_robot::amclPose >::value();
  }
  static const char* value(const ::mobile_robot::amclPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOBILE_ROBOT_MESSAGE_AMCLPOSE_H
