obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01
inflation_radius: 2
cost_scaling_factor: 10
observation_sources: scan
scan:
  sensor_frame: base_link
  data_type: LaserScan
  topic: front/scan
  marking: true
  clearing: true
  min_obstacle_height: 0.25
  max_obstacle_height: 0.3
  observation_persitence: 0.0
