// Generated by gencpp from file mobile_robot/amclPoseRequest.msg
// DO NOT EDIT!


#ifndef MOBILE_ROBOT_MESSAGE_AMCLPOSEREQUEST_H
#define MOBILE_ROBOT_MESSAGE_AMCLPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_robot
{
template <class ContainerAllocator>
struct amclPoseRequest_
{
  typedef amclPoseRequest_<ContainerAllocator> Type;

  amclPoseRequest_()
    : getPose(false)  {
    }
  amclPoseRequest_(const ContainerAllocator& _alloc)
    : getPose(false)  {
  (void)_alloc;
    }



   typedef uint8_t _getPose_type;
  _getPose_type getPose;





  typedef boost::shared_ptr< ::mobile_robot::amclPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_robot::amclPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct amclPoseRequest_

typedef ::mobile_robot::amclPoseRequest_<std::allocator<void> > amclPoseRequest;

typedef boost::shared_ptr< ::mobile_robot::amclPoseRequest > amclPoseRequestPtr;
typedef boost::shared_ptr< ::mobile_robot::amclPoseRequest const> amclPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_robot::amclPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_robot::amclPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_robot::amclPoseRequest_<ContainerAllocator1> & lhs, const ::mobile_robot::amclPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.getPose == rhs.getPose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_robot::amclPoseRequest_<ContainerAllocator1> & lhs, const ::mobile_robot::amclPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::amclPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::amclPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::amclPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::amclPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::amclPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::amclPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_robot::amclPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9559bd3229841b2a55acb588ffb4beec";
  }

  static const char* value(const ::mobile_robot::amclPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9559bd3229841b2aULL;
  static const uint64_t static_value2 = 0x55acb588ffb4beecULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_robot::amclPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_robot/amclPoseRequest";
  }

  static const char* value(const ::mobile_robot::amclPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_robot::amclPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool getPose\n"
;
  }

  static const char* value(const ::mobile_robot::amclPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_robot::amclPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.getPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct amclPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_robot::amclPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_robot::amclPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "getPose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.getPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_ROBOT_MESSAGE_AMCLPOSEREQUEST_H
